-- SECTION 6: MIXED / CHALLENGE TASKS

use bikestores;

-- TASK 36: For each state, find the total number of customers AND the total revenue generated by those customers

SELECT c.state,
       COUNT(DISTINCT c.customer_id) AS customer_count,
       SUM(oi.quantity * oi.list_price * (1 - oi.discount)) AS total_revenue
FROM sales.customers c
LEFT JOIN sales.orders o ON c.customer_id = o.customer_id
LEFT JOIN sales.order_items oi ON o.order_id = oi.order_id
GROUP BY c.state
ORDER BY total_revenue DESC;

-- TASK 37: Rank all products by price within each category

SELECT p.product_name,
       c.category_name,
       p.list_price,
       RANK() OVER (PARTITION BY c.category_id ORDER BY p.list_price DESC) AS price_rank
FROM production.products p
JOIN production.categories c ON p.category_id = c.category_id;

-- TASK 38: Find the month-wise order count and total revenue for the year 2017

SELECT MONTH(o.order_date) AS month_number,
       COUNT(DISTINCT o.order_id) AS order_count,
       SUM(oi.quantity * oi.list_price * (1 - oi.discount)) AS total_revenue
FROM sales.orders o
JOIN sales.order_items oi ON o.order_id = oi.order_id
WHERE YEAR(o.order_date) = 2017
GROUP BY MONTH(o.order_date)
ORDER BY month_number;

-- TASK 39: List each store's best-selling product (by quantity sold)

WITH store_product_sales AS (
    SELECT st.store_id,
           st.store_name,
           p.product_name,
           SUM(oi.quantity) AS total_quantity_sold,
           ROW_NUMBER() OVER (PARTITION BY st.store_id ORDER BY SUM(oi.quantity) DESC) AS rank
    FROM sales.stores st
    JOIN sales.orders o ON st.store_id = o.store_id
    JOIN sales.order_items oi ON o.order_id = oi.order_id
    JOIN production.products p ON oi.product_id = p.product_id
    GROUP BY st.store_id, st.store_name, p.product_name
)
SELECT store_name, product_name, total_quantity_sold
FROM store_product_sales
WHERE rank = 1;

-- TASK 40: Report showing: store name, staff name, number of orders, and total revenue - grouped by store and staff member, sorted by revenue descending

SELECT st.store_name,
       s.first_name + ' ' + s.last_name AS staff_name,
       COUNT(DISTINCT o.order_id) AS order_count,
       SUM(oi.quantity * oi.list_price * (1 - oi.discount)) AS total_revenue
FROM sales.stores st
JOIN sales.staffs s ON st.store_id = s.store_id
JOIN sales.orders o ON s.staff_id = o.staff_id
JOIN sales.order_items oi ON o.order_id = oi.order_id
GROUP BY st.store_name, s.first_name, s.last_name
ORDER BY total_revenue DESC;

-- EnD